LOADING THE DATASET

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/dataset_processed_train.csv')
df2=pd.read_csv('/content/drive/MyDrive/amazon_electronics.csv')
df.head(5)

,review/text,review/length,review/score,sentiment_score,review/helpfulness,numer,denom,full_weights
0,El yay Super fast delivery! Love this movie. ...,173,5.0,0.6792,0.0,0.0,3.0,18.750000
1,Stock Hollywood - but strangely entertaining A...,1567,4.0,0.9851,1.0,2.0,2.0,10.666667
2,The Time Machine Good special effects for the ...,190,4.0,0.9127,1.0,3.0,3.0,18.750000
3,Samurai I was very resistant to see this movie...,1866,4.0,0.9743,0.6,3.0,5.0,20.416667
4,'I'm going back to my own time. I won't even ...,6003,5.0,0.9989,0.6,3.0,5.0,20.416667

In [ ]:
df.tail(5)

,review/text,review/length,review/score,sentiment_score,review/helpfulness,numer,denom,full_weights
3430883,A great feel good movie. Bend it like Beckham ...,1975,4.0,0.9906,0.500000,5.0,10.0,40.0
3430884,"A journey of hope, faith and gaining a positiv...",2390,5.0,0.9951,0.500000,1.0,2.0,8.0
3430885,You Destroy the Thing You Love If one were to ...,1711,5.0,0.9816,0.500000,1.0,2.0,8.0
3430886,Light-hearted 80's Sports Movie Just as the ti...,276,4.0,0.8834,0.000000,0.0,4.0,28.8
3430887,Loved it ! These are the kind of Movies that a...,271,4.0,0.8436,0.333333,1.0,3.0,12.5

In [ ]:
df.sample(5)

,review/text,review/length,review/score,sentiment_score,review/helpfulness,numer,denom,full_weights
2728486,Very decent movie crime in a small town. I had...,1344,4.0,0.6010,0.833333,5.0,6.0,32.000000
2211609,GO OUT AND BY THIS DVD/VHS NOW! i have never l...,969,5.0,0.9872,1.000000,2.0,2.0,10.666667
1874059,Good comedic take on life in the military Unli...,615,4.0,0.9468,0.500000,1.0,2.0,8.000000
1897407,I love it I recommend this item to all custome...,124,5.0,0.9100,0.000000,0.0,3.0,18.750000
608690,Schwarzeneggar's WORST Do not see this movie. ...,648,1.0,-0.9834,0.214286,3.0,14.0,74.666667

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3430888 entries, 0 to 3430887
Data columns (total 8 columns):
 #   Column              Dtype
---  ------              -----
 0   review/text         object
 1   review/length       int64
 2   review/score        float64
 3   sentiment_score     float64
 4   review/helpfulness  float64
 5   numer               float64
 6   denom               float64
 7   full_weights        float64
dtypes: float64(6), int64(1), object(1)
memory usage: 209.4+ MB

In [ ]:
df.describe()

,review/length,review/score,sentiment_score,review/helpfulness,numer,denom,full_weights
count,3.430888e+06,3.430888e+06,3.430888e+06,3.430888e+06,3.430888e+06,3.430888e+06,3.430888e+06
mean,1.168034e+03,3.854771e+00,5.269320e-01,6.237778e-01,6.476207e+00,9.942798e+00,1.014778e+02
std,1.234575e+03,1.413848e+00,6.780703e-01,3.250653e-01,1.924870e+01,2.256757e+01,7.237791e+02
min,1.000000e+01,1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,8.000000e+00
25%,3.760000e+02,3.000000e+00,3.459000e-01,4.000000e-01,1.000000e+00,3.000000e+00,1.250000e+01
50%,7.640000e+02,4.000000e+00,9.076000e-01,6.666667e-01,3.000000e+00,5.000000e+00,2.450000e+01
75%,1.512000e+03,5.000000e+00,9.773000e-01,9.729730e-01,6.000000e+00,9.000000e+00,5.485714e+01
max,3.307600e+04,5.000000e+00,1.000000e+00,1.000000e+00,9.520000e+02,9.950000e+02,4.102390e+05

In [ ]:
df.shape

(3430888, 8)

COLUMNS NAMES

In [ ]:
df.columns

Index(['review/text', 'review/length', 'review/score', 'sentiment_score',
       'review/helpfulness', 'numer', 'denom', 'full_weights'],
      dtype='object')

REMOVING THE UNNECESSARY COLUMNS

In [ ]:
df=df.drop(columns=[ 'review/length', 'sentiment_score',
       'review/helpfulness', 'numer', 'denom', 'full_weights'])

CHECKING NULL VALUES

In [ ]:
df.isnull().sum()

review/text     0
review/score    0
dtype: int64

REMOVING NULL VALUES

In [ ]:
df.dropna(inplace=True)

CHECKING DUPLICATES

In [ ]:
print(df.duplicated().sum())

2431411

DROPPING DUPLICATES

In [ ]:
df.drop_duplicates(subset=['review/text','review/score'],inplace=True)

RENAMING THE COLUMNS

In [ ]:
df.rename(columns={'review/text':'review','review/score':'rating'},inplace=True)

In [ ]:
df['rating'].astype(int)

0          5
1          4
2          4
3          4
4          5
          ..
3430860    5
3430862    5
3430872    5
3430879    5
3430882    4
Name: rating, Length: 999477, dtype: int64

REMOVING EMOJIS,LINKS

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df.loc[:, "review"] = df["review"].apply(clean_text)

In [ ]:
df['rating'].value_counts()

rating
5.0    497810
4.0    190895
1.0    123019
3.0    110419
2.0     77334
Name: count, dtype: int64

SORTING THE DATA

In [ ]:
df.sort_values(by='rating',ascending=True,inplace=True)

In [ ]:
df.shape

(999477, 2)

In [ ]:
df2.head(5)

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
0,US,22873041,R3ARRMDEGED8RD,B00KJWQIIC,335625766,Plemo 14-Inch Laptop Sleeve Case Waterproof Fa...,PC,5,0,0,N,Y,Pleasantly surprised,I was very surprised at the high quality of th...,2015-08-31,1
1,US,30088427,RQ28TSA020Y6J,B013ALA9LA,671157305,TP-Link OnHub AC1900 Wireless Wi-Fi Router,PC,5,24,31,N,N,OnHub is a pretty no nonsense type router that...,I am a Google employee and had to chance to us...,2015-08-31,1
2,US,20329786,RUXJRZCT6953M,B00PML2GQ8,982036237,AmazonBasics USB 3.0 A Male to A Male Cable - ...,PC,1,2,2,N,N,None of them worked. No functionality at all.,"Bought cables in 3ft, 6ft and 9ft. NONE of th...",2015-08-31,0
3,US,14215710,R7EO0UO6BPB71,B001NS0OZ4,576587596,Transcend P8 15-in-1 USB 2.0 Flash Memory Card...,PC,1,0,0,N,Y,just keep searching.,"nope, cheap and slow",2015-08-31,0
4,US,38264512,R39NJY2YJ1JFSV,B00AQMTND2,964759214,Aleratec SATA Data Cable 2.0 20in Serial ATA S...,PC,5,0,0,N,Y,Five Stars,Excellent! Great value and does the job.,2015-08-31,1

In [ ]:
df2.tail(5)

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
6906559,US,51995596,R3N6GRSJKEASQP,B00000J3II,672369061,Iomega 10919 Zip 100 Drive (Parallel Port),PC,5,4,4,N,N,Sturdy and Useful.,I've owned the Zip drive for 3 years already a...,1999-07-10,1
6906560,US,51709569,R3D1N3J5SXSYPF,B00000J3II,672369061,Iomega 10919 Zip 100 Drive (Parallel Port),PC,4,1,2,N,N,"good, but could be better",i bought one of these to backup my ever growin...,1999-07-02,1
6906561,US,52013515,R2X34TXZ6RML4Q,B00000J3II,672369061,Iomega 10919 Zip 100 Drive (Parallel Port),PC,3,5,5,N,N,"Nice for beginners, JAZ is better",I bought this because my hard drive was runnin...,1999-07-02,0
6906562,US,52851668,R3AZ2KXYCYXMYL,B00000JBHA,865091807,Yamaha YSTMS28W Multimedia Speakers,PC,5,15,15,N,N,"great sounding deep bass, clear highend, nothi...",i use these speakers with my macintosh pc and ...,1999-07-01,1
6906563,US,52133593,R331BOV1QBPB9D,B00000JDFI,978603818,Belkin Pro Series Parallel Printer Cable (25 F...,PC,5,12,13,N,N,One nice cable,"Belkin cables are the best! They have big, ea...",1999-07-01,1

In [ ]:
df2.sample(5)

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date,sentiment
712278,US,14789049,RPVE1LYJFSI73,B004HXVMIA,474480263,Battpit&trade; New Replacement Laptop / Notebo...,PC,3,0,0,N,Y,Three Stars,just a replacement....all the same...don't buy...,2015-05-22,0
3021627,US,49599647,R1TI3V3LAK6IEC,B003TO56F8,937272644,Livescribe Smartpen Portfolio,PC,5,1,1,N,N,A must have for professional look,I'm a well into my career ( translation old an...,2014-07-07,1
4050832,US,24014122,R238UV3PH53XVE,B00BWYQ9YE,270050908,"Kindle Fire HDX 7"", HDX Display (Previous Gene...",PC,4,1,2,N,Y,APPLE GUY CATCHING FIRE,I originally gave this product a three as I'm ...,2013-11-22,1
2410613,US,9603025,R1JTJQ2CJPASXQ,B0015TJNEY,906228795,SANOXY® WEBCAM,PC,2,0,0,N,Y,cheaply made but works ok -needs better softwa...,bottom stand is cheap and broke off a about 1 ...,2014-10-16,0
6164024,US,12372294,R1E8OSTS95UGAY,B003E8JE02,264578854,Pink Solid Color Soft Silicone Skin Apple Ipad...,PC,5,0,0,N,Y,ipad skin,You get what you pay for. its not going to pro...,2011-06-27,1

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6906564 entries, 0 to 6906563
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   marketplace        object
 1   customer_id        int64
 2   review_id          object
 3   product_id         object
 4   product_parent     int64
 5   product_title      object
 6   product_category   object
 7   star_rating        int64
 8   helpful_votes      int64
 9   total_votes        int64
 10  vine               object
 11  verified_purchase  object
 12  review_headline    object
 13  review_body        object
 14  review_date        object
 15  sentiment          int64
dtypes: int64(6), object(10)
memory usage: 843.1+ MB

In [ ]:
df2.describe()

,customer_id,product_parent,star_rating,helpful_votes,total_votes,sentiment
count,6.906564e+06,6.906564e+06,6.906564e+06,6.906564e+06,6.906564e+06,6.906564e+06
mean,2.799257e+07,4.916634e+08,4.086461e+00,1.484451e+00,1.962077e+00,7.636062e-01
std,1.557220e+07,2.890112e+08,1.362854e+00,4.149143e+01,4.307079e+01,4.248668e-01
min,1.001600e+04,1.602000e+03,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.442019e+07,2.428900e+08,4.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
50%,2.678854e+07,4.884428e+08,5.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,4.266215e+07,7.429021e+08,5.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
max,5.309658e+07,9.999960e+08,5.000000e+00,4.752400e+04,4.836200e+04,1.000000e+00

In [ ]:
df2.shape

(6906564, 16)

COLUMNS NAMES

In [ ]:
df2.columns

Index(['marketplace', 'customer_id', 'review_id', 'product_id',
       'product_parent', 'product_title', 'product_category', 'star_rating',
       'helpful_votes', 'total_votes', 'vine', 'verified_purchase',
       'review_headline', 'review_body', 'review_date', 'sentiment'],
      dtype='object')

REMOVING THE UNNECESSARY COLUMNS

In [ ]:
df2=df2.drop(columns=['marketplace', 'customer_id', 'review_id', 'product_id',
       'product_parent', 'product_title', 'product_category',
       'helpful_votes', 'total_votes', 'vine', 'verified_purchase',
       'review_headline', 'review_date', 'sentiment'])

RENAMING THE COLUMNS

In [ ]:
df2.rename(columns={'review_body':'review','star_rating':'rating'},inplace=True)

CHECKING NULL VALUES

In [ ]:
df2.isnull().sum()

rating      0
review    120
dtype: int64

REMOVING NULL VALUES

In [ ]:
df2.dropna(inplace=True)

CHECKING DUPLICATES

In [ ]:
print(df2.duplicated().sum())

500523

DROPPING DUPLICATES

In [ ]:
df2.drop_duplicates(subset=['review','rating'],inplace=True)

In [ ]:
df2['rating'].astype(int)

0          5
1          5
2          1
3          1
4          5
          ..
6906559    5
6906560    4
6906561    3
6906562    5
6906563    5
Name: rating, Length: 6405921, dtype: int64

REMOVING EMOJIS,LINKS

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df2.loc[:, "review"] = df2["review"].apply(clean_text)

In [ ]:
df2['rating'].value_counts()

rating
5    3694309
4    1110817
1     740559
3     501390
2     358846
Name: count, dtype: int64

SORTING THE DATA

In [ ]:
df2.sort_values(by='rating',ascending=True,inplace=True)

In [ ]:
cols = list(df2.columns)

i, j = cols.index('review'), cols.index('rating')
cols[i], cols[j] = cols[j], cols[i]
df2 = df2[cols]

In [ ]:
df2.shape

(6405921, 2)

MERGING DATASETS

In [ ]:
dl_merge_df = pd.concat([df, df2], ignore_index=True)

In [ ]:
dl_merge_df.shape

(7405398, 2)

In [ ]:
dl_merge_df.head(5)

                                              review  rating
0  i really wanted to like it but i cant ignore t...     1.0
1  not what i expected i bought it thinking i cou...     1.0
2  who approved the cover art movie stars cover a...     1.0
3  stick with the book the book was amazing movie...     1.0
4  horrendous waste of time and money i had purch...     1.0

In [ ]:
dl_merge_df['rating'].value_counts()

rating
5.0    4192119
4.0    1301712
1.0     863578
3.0     611809
2.0     436180
Name: count, dtype: int64

CREATING A BALANCED DATASET

In [ ]:
import pandas as pd
bal_df = (dl_merge_df.groupby('rating', group_keys=False)
  .apply(lambda x: x.sample(n=150000, random_state=42)))

remain_df=dl_merge_df.drop(bal_df.index)


bal_df= bal_df.reset_index(drop=True)
remain_df=remain_df.reset_index(drop=True)

/tmp/ipython-input-1653092398.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=150000, random_state=42)))

In [ ]:
bal_df['rating'].value_counts()

rating
1.0    150000
2.0    150000
3.0    150000
4.0    150000
5.0    150000
Name: count, dtype: int64

In [ ]:
remain_df['rating'].value_counts()

rating
5.0    4042119
4.0    1151712
1.0     713578
3.0     461809
2.0     286180
Name: count, dtype: int64

In [ ]:
remain_df = remain_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Desired sample sizes based on % targets
target_counts = {
    5: 858540,
    4: 715450,
    3: 429270,
    2: 286180,
    1: 572360

}

# Apply sampling
sampled = []

for rating, count in target_counts.items():
    group = remain_df[remain_df['rating'] == rating]
    sampled.append(group.iloc[:count])  # get top N

final_df = pd.concat(sampled).reset_index(drop=True)

# Check result
print(final_df['rating'].value_counts(normalize=True) * 100)  # % distribution

rating
5.0    30.0
4.0    25.0
1.0    20.0
3.0    15.0
2.0    10.0
Name: proportion, dtype: float64

In [ ]:
final_df['rating'].value_counts()

rating
5.0    858540
4.0    715450
1.0    572360
3.0    429270
2.0    286180
Name: count, dtype: int64

SAVING THE DATASETS

In [ ]:
bal_df.to_csv('DL_Balanced_dataset.csv',index=False)
final_df.to_csv('DL_Remaining_df.csv',index=False)