LOADING THE DATASET

In [ ]:
import pandas as pd
df1=pd.read_csv('/content/train.csv')

In [ ]:
print("df1 datasets")
df.head(5)

df1 datasets

                                              review  rating
0  very good value and a great tv very happy and ...       5
1           after month still cant access my account       3
2  i couldnt make an official review on a product...       1
3  fantastic extremely easy to use website fantas...       5
4  so far annoyed as hell with this bt monthly pa...       1

In [ ]:
df.sample(5)

                                                  review  rating
13195  appalling experience ordered food it did nit a...       1
3079       easy to order quick delivery and good quality       5
16300  excellent service and delivery by cex i impres...       5
15415  they were prompt with my logo i will use them ...       5
10176  talktalk is fine if nothing goes wrong otherwi...       1

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Id      60000 non-null  int64
 1   Review  60000 non-null  object
 2   Rating  60000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.4+ MB

In [ ]:
df1.shape

(60000, 3)

In [ ]:
df1.columns

Index(['Id', 'Review', 'Rating'], dtype='object')

REMOVING THE UNNECESSARY COLUMNS

In [ ]:
df1.drop('Id',axis=1,inplace=True)

In [ ]:
df1.head(5)

                                              Review  Rating
0  Very good value and a great tv very happy and ...       5
1        After 6 month still can't access my account       3
2  I couldn't make an official review on a produc...       1
3  Fantastic! Extremely easy to use website, fant...       5
4  So far annoyed as hell with this bt monthly pa...       1

CHECKING THE NULL VALUES

In [ ]:
df1.isnull().sum()

Review    0
Rating    0
dtype: int64

REMOVING THE NULL VALUES

In [ ]:
df1.dropna(inplace=True)

CHECKING  DUPLICATES

In [ ]:
print(df1.duplicated().sum())

24

DROPPING THE DUPLICATES

In [ ]:
df1.drop_duplicates(subset=['Rating','Review'],inplace=True)

RENAMING THE COLUMNS

In [ ]:
df1.rename(columns={'Review':'review','Rating':'rating'},inplace=True)

In [ ]:
df1['rating']=df1['rating'].astype(int)

REMOVING EMOJI,LINKS

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df1.loc[:, "review"] = df1["review"].apply(clean_text)

In [ ]:
df1['rating'].value_counts()

rating
5    34659
1    18660
4     3349
3     1679
2     1629
Name: count, dtype: int64

In [ ]:
df1.shape

(59976, 2)

In [ ]:
df1.to_csv('clean_imbal2.csv',index=False)

In [ ]:
df2=pd.read_csv('/content/tripadvisor_hotel_reviews.csv')
df2.head(5)

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20491 entries, 0 to 20490
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  20491 non-null  object
 1   Rating  20491 non-null  int64
dtypes: int64(1), object(1)
memory usage: 320.3+ KB

In [ ]:
df2.describe()

             Rating
count  20491.000000
mean       3.952223
std        1.233030
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000

In [ ]:
df2.shape

(20491, 2)

In [ ]:
df2.columns

Index(['Review', 'Rating'], dtype='object')

In [ ]:
df2.isnull().sum()

Review    0
Rating    0
dtype: int64

In [ ]:
print(df2.duplicated().sum())

0

In [ ]:
df2.drop_duplicates(subset=['Review','Rating'],inplace=True)

In [ ]:
df2['Rating']=df2['Rating'].astype(int)

In [ ]:
df2['Rating'].value_counts()

Rating
5    9054
4    6039
3    2184
2    1793
1    1421
Name: count, dtype: int64

In [ ]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df2.loc[:, "Review"] = df2["Review"].apply(clean_text)

In [ ]:
df2.shape

(20491, 2)

In [ ]:
df2.to_csv('tripadvisor.csv',index=False)

In [ ]:
mg1=pd.read_csv('/content/clean_imbal2.csv')
mg2=pd.read_csv('/content/tripadvisor.csv')
mg3=pd.read_csv('/content/Remaining_df.csv')
print(mg1.columns)
print(mg2.columns)
print(mg3.columns)

Index(['review', 'rating'], dtype='object')
Index(['Review', 'Rating'], dtype='object')
Index(['rating', 'review'], dtype='object')

In [ ]:
cols = list(df1.columns)

i, j = cols.index('review'), cols.index('rating')
cols[i], cols[j] = cols[j], cols[i]
mg1 = mg1[cols]

In [ ]:
mg2.rename(columns={'Review':'review','Rating':'rating'},inplace=True)
cols = list(df1.columns)

i, j = cols.index('review'), cols.index('rating')
cols[i], cols[j] = cols[j], cols[i]
mg2= mg2[cols]

In [ ]:

imbal = pd.concat([mg1,mg2,mg3], ignore_index=True)

In [ ]:
imbal.shape

(133147, 2)

In [ ]:
imbal.head(5)

   rating                                             review
0       5  very good value and a great tv very happy and ...
1       3           after month still cant access my account
2       1  i couldnt make an official review on a product...
3       5  fantastic extremely easy to use website fantas...
4       1  so far annoyed as hell with this bt monthly pa...

In [ ]:
imbal.isnull().sum()

rating    0
review    2
dtype: int64

In [ ]:
imbal.dropna(inplace=True)

In [ ]:
print(imbal.duplicated().sum())

28

In [ ]:
imbal.drop_duplicates(subset=['review','rating'],inplace=True)

In [ ]:
imbal['rating'].value_counts()

rating
5    82276
1    20512
4    19326
3     7349
2     3654
Name: count, dtype: int64

In [ ]:
imbal.shape

(133117, 2)

saving the dataset

In [ ]:
imbal.to_csv('imbalanced-dataset.csv',index=False)